application: gae-starterpack-2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: hos_api.APPLICATION
- url: /frontend
  static_dir: frontend
- url: /.*
  script: hos_main.application


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
